import test from "node:test";
import assert from "node:assert/strict";
import { renderAgentsBootstrap } from "../src/init.js";

test("AGENTS bootstrap points first-run agents at governed MCP, specs, and skills", () => {
  const content = renderAgentsBootstrap(
    "https://specreg.example.com",
    "Web App Standard",
    "github.com/acme/app",
    "specs",
    ".spec/skills"
  );

  assert.match(content, /generated by SpecRegistry bootstrap/);
  assert.match(content, /SPECREGISTRY\.md/);
  assert.match(content, /specreg mcp/);
  assert.match(content, /specreg check/);
  assert.match(content, /get_specs/);
  assert.match(content, /github\.com\/acme\/app/);
  assert.match(content, /\.spec\/skills/);
  assert.match(content, /check_compliance/);
  assert.match(content, /specreg comply/);
  assert.match(content, /halt before claiming completion/);
  assert.match(content, /exact tool or command output/);
  assert.match(content, /Do not blanket-map files to `PROJECT_PROFILE\.md`/);
  assert.match(content, /missing-guidance gap/);
});
