import fs from "node:fs";
import path from "node:path";
import { fetchJson, selectProjectType } from "./registry.js";
import { repoIdentity } from "./repo.js";

const GENERATED_MARKER = "<!-- generated by SpecRegistry";
export const COMPILE_TARGETS = ["claude", "agents", "cursor"] as const;
export type CompileTarget = (typeof COMPILE_TARGETS)[number];

interface CompileResponse {
  target_filename: string;
  content: string;
  specs: Array<{ filename: string; version: string }>;
}

export interface CompileOptions {
  server: string;
  token?: string;
  type?: string;
  dir: string;
  target: CompileTarget;
  force?: boolean;
}

function manifestPath(dir: string): string {
  return path.resolve(process.cwd(), dir, ".specregistry.json");
}

function projectTypeFromManifest(dir: string): string | undefined {
  try {
    return (JSON.parse(fs.readFileSync(manifestPath(dir), "utf8")) as { project_type?: string }).project_type;
  } catch {
    return undefined;
  }
}

/** Remember compile targets in the manifest so `specreg sync` regenerates them. */
export function rememberCompileTarget(dir: string, target: CompileTarget): void {
  try {
    const file = manifestPath(dir);
    const manifest = JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
    const targets = new Set([...(Array.isArray(manifest.compile_targets) ? manifest.compile_targets : []), target]);
    manifest.compile_targets = [...targets];
    fs.writeFileSync(file, JSON.stringify(manifest, null, 2) + "\n");
  } catch {
    // no manifest yet — compile still works, it just won't auto-regenerate
  }
}

export function savedCompileTargets(dir: string): CompileTarget[] {
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath(dir), "utf8")) as { compile_targets?: string[] };
    return (manifest.compile_targets ?? []).filter((t): t is CompileTarget =>
      (COMPILE_TARGETS as readonly string[]).includes(t)
    );
  } catch {
    return [];
  }
}

export async function runCompile(opts: CompileOptions): Promise<void> {
  const typeName =
    opts.type ?? projectTypeFromManifest(opts.dir) ?? (await selectProjectType(opts.server, undefined, opts.token)).name;
  const identity = repoIdentity();
  const params = new URLSearchParams({ target: opts.target, repo: identity.repo });

  const compiled = await fetchJson<CompileResponse>(
    `${opts.server}/api/v1/specs/${encodeURIComponent(typeName)}/compile?${params}`,
    undefined,
    opts.token
  );

  const outPath = path.resolve(process.cwd(), compiled.target_filename);
  if (fs.existsSync(outPath) && !opts.force) {
    const existing = fs.readFileSync(outPath, "utf8");
    if (!existing.includes(GENERATED_MARKER)) {
      throw new Error(
        `${compiled.target_filename} already exists and was not generated by SpecRegistry. ` +
          `Use --force to overwrite it.`
      );
    }
  }
  fs.writeFileSync(outPath, compiled.content);
  rememberCompileTarget(opts.dir, opts.target);
  console.log(
    `Wrote ${compiled.target_filename} (${compiled.specs.map((s) => `${s.filename}@${s.version}`).join(", ")})`
  );
}
